dist/objects/Actual_Burndown_Week__c.object
<CustomObject>
    <label>Actual Burndown Week</label>
    <nameField>
        <displayFormat>ABW-{000000}</displayFormat>
        <label>Actual Burndown Week Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actual Burndown Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Feature_Forecast__c</fullName>
        <label>Feature Forecast</label>
        <referenceTo>Feature_Forecast__c</referenceTo>
        <relationshipLabel>Actual Burndown Weeks</relationshipLabel>
        <relationshipName>Actual_Burndown_Weeks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Remaining_Stories__c</fullName>
        <label>Remaining Stories</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <type>Date</type>
    </fields>
</CustomObject>

dist/objects/Feature_Forecast__c.object
<CustomObject>
    <label>Feature Forecast</label>
    <nameField>
        <displayFormat>FF-{000000}</displayFormat>
        <label>Feature Forecast Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feature Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dist/objects/Simulation_Burndown__c.object
<CustomObject>
    <label>Simulation Burndown</label>
    <nameField>
        <displayFormat>SB-{000000}</displayFormat>
        <label>Simulation Burndown Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Simulation Burndowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Feature_Forecast__c</fullName>
        <label>Feature Forecast</label>
        <referenceTo>Feature_Forecast__c</referenceTo>
        <relationshipLabel>Simulation Burndowns</relationshipLabel>
        <relationshipName>Simulation_Burndowns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

dist/objects/Simulation_Burndown_Week__c.object
<CustomObject>
    <label>Simulation Burndown Week</label>
    <nameField>
        <displayFormat>SBW-{000000}</displayFormat>
        <label>Simulation Burndown Week Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Simulation Burndown Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Remaining_Stories__c</fullName>
        <label>Remaining Stories</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Simulation_Burndown__c</fullName>
        <label>Simulation Burndown</label>
        <referenceTo>Simulation_Burndown__c</referenceTo>
        <relationshipLabel>Simulation Burndown Weeks</relationshipLabel>
        <relationshipName>Simulation_Burndown_Weeks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <required>true</required>
        <type>Date</type>
    </fields>
</CustomObject>

dist/objects/Simulation_Week__c.object
<CustomObject>
    <label>Simulation Week</label>
    <nameField>
        <displayFormat>SW-{000000}</displayFormat>
        <label>Simulation Week Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Simulation Weeks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Feature_Forecast__c</fullName>
        <label>Feature Forecast</label>
        <referenceTo>Feature_Forecast__c</referenceTo>
        <relationshipLabel>Simulation Weeks</relationshipLabel>
        <relationshipName>Simulation_Weeks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <inlineHelpText>Probability that all stories will be completed by this week</inlineHelpText>
        <label>Probability</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Week_Number__c</fullName>
        <inlineHelpText>Number of sprints since start date</inlineHelpText>
        <label>Sprint Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week__c</fullName>
        <label>Week</label>
        <required>true</required>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ForecastEditorController.cls
public with sharing class ForecastEditorController {
@AuraEnabled
public static Map<String, Object> EditForecast(Feature_Forecast__c forecast, List<Simulation_Week__c> simulationWeeks, List<Simulation_Burndown__c> simulationBurns, String simulationBurnWeeks){
	Map<String, Object> results = new Map<String, Object>();
	upsert forecast;
	results.put('forecast', forecast);
	delete [SELECT Id From Simulation_Week__c WHERE Feature_Forecast__c = : forecast.Id];
	for(Simulation_Week__c simulationWeek : simulationWeeks) {
		simulationWeek.Feature_Forecast__c = forecast.Id;
	}
	insert simulationWeeks;
	results.put('simulationWeeks', simulationWeeks);
	delete [SELECT Id FROM Simulation_Burndown_Week__c WHERE Simulation_Burndown__r.Feature_Forecast__c = : forecast.Id];
	delete [SELECT Id FROM Simulation_Burndown__c WHERE Feature_Forecast__c = : forecast.Id];
	System.debug(simulationBurns);
	for(Simulation_Burndown__c simulationBurn : simulationBurns) {
		simulationBurn.Feature_Forecast__c = forecast.Id;
	}
	insert simulationBurns;
	System.debug(simulationBurnWeeks);
	List<Simulation_Burndown_Week__c> burnWeeks = new List<Simulation_Burndown_Week__c>();
	List<List<Simulation_Burndown_Week__c> > desWeeks = (List<List<Simulation_Burndown_Week__c> >)JSON.deserialize(simulationBurnWeeks, List<List<Simulation_Burndown_Week__c> >.class);
	for(Integer i = 0; i < desWeeks.size(); i++) {
		Simulation_Burndown__c burn = simulationBurns[i];
		System.debug(desWeeks[i]);
		List<Simulation_Burndown_Week__c> weeks = desWeeks[i];

		for(Simulation_Burndown_Week__c burnWeek : weeks) {
			burnWeek.Simulation_Burndown__c = burn.Id;
			burnWeeks.add(burnWeek);
		}


	}
	insert burnWeeks;
	return results;
}

@AuraEnabled
public static Map<String, Object> LoadForecast(String recordId){
	Map<String, Object> results = new Map<String, Object>();
	List<Simulation_Week__c> simulationWeeks = GetSimulationWeeks(recordId);
	results.put('simulationWeeks', simulationWeeks);
	List<Simulation_Burndown__c> simulationBurndowns = GetBurndowns(recordId);
	results.put('simulationBurndowns', simulationBurndowns);
	List<Actual_Burndown_Week__c> actualBurndownWeeks = GetActualBurndownWeeks(recordId);
	results.put('actualBurndownWeeks', actualBurndownWeeks);
	return results;
}

@AuraEnabled
public static List<Simulation_Burndown__c> GetBurndowns(String recordId){
	return [SELECT Id, Feature_Forecast__c, (SELECT Id, Simulation_Burndown__c, Remaining_Stories__c, Week__c FROM Simulation_Burndown_Weeks__r ORDER BY Week__c) FROM Simulation_Burndown__c WHERE Feature_Forecast__c = : recordId];
}

@AuraEnabled
public static List<Simulation_Week__c> GetSimulationWeeks(String recordId){
	return [SELECT Id, Frequency__c, Probability__c, Week_Number__c, Week__c FROM Simulation_Week__c WHERE Feature_Forecast__c = : recordId ORDER BY Probability__c desc];
}

@AuraEnabled
public static List<Actual_Burndown_Week__c> GetActualBurndownWeeks(String recordId){
	return [SELECT Id, Week__c, Remaining_Stories__c FROM Actual_Burndown_Week__c ORDER BY Week__c];
}



}